### ISSUE TITLE
tb -h problem

### ISSUE THREAD

**Issue by presentoccupant** [klauscfhq/taskbook#46] opened 2018-08-03 19:10 UTC
**Describe the bug**
tb -h doesn't work the same as tb --help

**To Reproduce**
type tb --help and observe the output
type tb -h and observe the output

**Expected behavior**
Outputs should be the same

**Screenshots**
none

**Technical Info (please complete the following information)**
 - OS: macOS 10.13.4
 - Node.js Version: 10.7.0
 - Taskbook Version:  0.1.1

**Additional context**
I don't know JavaScript, but if I'm reading the code correctly then there's also a problem with "tb -v" (and I verified that that's true).

**Comment by taylorthurlow** [comment] 2018-08-03 19:24
Duplicate of #13.

**Comment by SakhirAtwi** [comment] 2018-08-04 08:40
Fixed at the pull request #53

**Closed** 2018-08-05 02:12 UTC
Labels: duplicate
